WILDCARD_TOKEN = "<*>"
NO_DIAC_TOKEN = "<no_diac>"
UNK_DIAC_TOKEN = "<unk_diac>"
PAD_TOKEN = "<pad>"
WORD_DELIMITER_TOKEN = "|"
UNK_TOKEN = "<unk>"
START_TOKEN = "<s>"
END_TOKEN = "</s>"

SPECIAL_TOKENS = [PAD_TOKEN, START_TOKEN, END_TOKEN, UNK_TOKEN, WORD_DELIMITER_TOKEN, NO_DIAC_TOKEN, UNK_DIAC_TOKEN]
